### ISSUE TITLE
Nav menu cut off on some widths

### ISSUE THREAD

**Issue by melanieseltzer** [255kb/mockoon-website#1]
Came across this small bug that's causing the nav to be cut off from 1200px - 1451px browser width. I believe it's an issue with Bulma's `flex-basis: 0` on .nav-right. Happy to submit a PR if you want.

<img width="960" alt="screen shot 2018-07-16 at 8 58 15 am" src="https://user-images.githubusercontent.com/17421347/42769385-e4276dec-88d6-11e8-89cb-c7dd42ce90fe.png">

**Comment by 255kb** [comment]
Thank you, problem solved by moving github button under the tagline 😄
